# Steps:
#  git clone --recursive https://github.com/triton-inference-server/dali_backend.git
#  modify the Dockerfile.release as below and then build the docker image

 RUN pip3 install -U pip
+RUN pip install opencv-python-headless numpy scipy Pillow torch torchvision tqdm
+
 WORKDIR /opt
